In [49]:
# Write a Python program to print the NumPy version in your system.
import numpy as np 
print(np.__version__)


1.21.5


In [2]:
# Write a Python program to reverse an array (first element becomes last).
import numpy as np
arr=np.array([3,5,6,7,9,11,15,17])
arr1=arr[::-1]
print(arr1)

[17 15 11  9  7  6  5  3]


In [7]:
# Write a Python program to convert a list and tuple into arrays. 
import numpy as np
lst =[3,5,6,7,9,11,15,17]
tup=(3,5,6,7,9,11,15,17)
arr1=np.array(lst)
arr2=np.array(tup)
print(arr1,type(arr1))
print(arr2,type(arr2))


[ 3  5  6  7  9 11 15 17] <class 'numpy.ndarray'>
[ 3  5  6  7  9 11 15 17] <class 'numpy.ndarray'>


In [10]:
# Write a Python program to find common values between two arrays.
import numpy as np
arr1=np.array([22,13,4,5,67,89,13,15,70])
arr2=np.array([1,15,34,23,67,89,12,61])
print("Common values in two arrays are :")
for i in arr1:
    if i in arr2:
        print(i)

Common values in two arrays are :
67
89
15


In [76]:
# Write a Python program compare two arrays using numpy.
a1=np.arange(0,9).reshape(3,3)
a2=np.arange(0,9)
np.array_equiv(a1,a2)

False

In [24]:
# Write a Python program to change the dimension of an array.
import numpy as np
arr=np.arange(1,13)
print(arr,f'\ndimension is {np.ndim(arr)}')
arr1=np.reshape(arr,(3,4))
print(arr1,f'\ndimension is {np.ndim(arr1)}')

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
dimension is 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
dimension is 2


In [14]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
import numpy as np
arr=np.arange(1,100)
lst=[]
for i in arr:
    if i%3==0 or i%5==0:
        lst.append(i)
arr2=np.array(lst)
print(sum(arr2))
        

2318


In [15]:
# Write a Python program to convert a NumPy array into Python list structure. 
import numpy as np
arr=np.arange(1,10)
lst=[]
for i in arr:
    lst.append(i)

print(lst,type(lst))

[1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [50]:
# Write a Python program to how to add an extra column to a numpy array.
import numpy as np
arr=np.array([[1,2,3],
            [2,4,5]])
arr1=np.array([[1],[3]])
print(np.concatenate((arr,arr1),axis=1))

[[1 2 3 1]
 [2 4 5 3]]


In [1]:
# Write a Python program to check whether the numpy array is empty or not
import numpy as np
arr=np.array([[1,2,3],
            [2,4,5]])
if len(arr)==0:
    print('its an empty array')
else:
    print('its not an empty array')

its not an empty array


In [17]:
# Write a Python program to normalize a 3x3 random matrix.
import numpy as np
arr=np.arange(0,36,4)
arr1=arr.reshape((3,3))
lst=[]
for i in arr1:
    total=0
    for j in i:
        total=total+j
    a=i/(total)
    lst.append(a)
norm_arr1=np.array(lst)
print(norm_arr1) # this is normalize by row side 

        
    

[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


In [ ]:
# How to ignore all numpy warnings (not recommended)?

In [40]:
# How to swap two rows of an array?
arr=np.arange(1,27,3).reshape(3,3)
print(arr)
a=arr[1]
b=arr[2]
arr1=np.array((arr[0],b,a))
print(f'\nafter swaping\n{arr1}')

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]

after swaping
[[ 1  4  7]
 [19 22 25]
 [10 13 16]]


In [59]:
# Python program to create a random vector of size 10 and sort it.
arr=np.random.rand(10)
print(np.sort(arr))

[0.35872779 0.36129306 0.36819045 0.47647031 0.66266889 0.68551197
 0.70310784 0.87987526 0.94546335 0.95067597]


In [75]:
# Write a Python program to check two random arrays are equal or not.
a1=np.arange(0,9).reshape(3,3)
a2=np.arange(10,19).reshape(3,3)
np.array_equal(a1,a2)

False

In [65]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.
a=np.arange(4,13,1).reshape(3,3)
print(f'first matrix\n{a}')
b=np.arange(24,42,2).reshape(3,3)
print(f'second matrix\n{b}')
print(f'add\n{a+b}')
print(f'sbtract\n{a-b}')
print(f'multifly\n{a*b}')
print(f'divide\n{a/b}')


first matrix
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
second matrix
[[24 26 28]
 [30 32 34]
 [36 38 40]]
add
[[28 31 34]
 [37 40 43]
 [46 49 52]]
sbtract
[[-20 -21 -22]
 [-23 -24 -25]
 [-26 -27 -28]]
multifly
[[ 96 130 168]
 [210 256 306]
 [360 418 480]]
divide
[[0.16666667 0.19230769 0.21428571]
 [0.23333333 0.25       0.26470588]
 [0.27777778 0.28947368 0.3       ]]


In [68]:
# Write a Python program to get the dates of yesterday, today and tomorrow.
today=np.datetime64('today')
print(f'today is {today}')
yesterday=np.datetime64('today')- np.timedelta64(1)
print(f'Yesterday is {yesterday}')
tom=np.datetime64('today')+ np.timedelta64(1)
print(f'tomorrow is {tom}')

today is 2022-06-25
Yesterday is 2022-06-24
tomorrow is 2022-06-26
